config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :posts
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery prepend: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    # search_parameter = 'Post'
    # @posts = Post.where("title like ?", search_parameter)
    search_parameter = "' OR '1'='1"
    @posts = Post.where("title like '%#{search_parameter}%'")
    # @posts = Post.all
    puts @posts.to_sql
  end

  def show; end
  def edit; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    # debugger
    @users = User.all.order(id: :desc)
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand me-5" href="/">Sequrity</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse ms-5" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= users_path %>">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_path %>">Create User</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= posts_path %>">Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_post_path %>">Create Post</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sequrity App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-light">
    <header class="container">
      <%= render 'layouts/nav' %>
    </header>
    <main class="container m-5 p-5 text-center">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="border rounded p-5 m-5">
  <%= simple_form_for(@post) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :title %>
    </div>
    <div class="form-inputs">
      <%= f.association :user %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="border rounded p-5 m-5">
  <h5 class="text-muted">
    Title
  </h5><br>
  <%= post.title %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div class="btn-group">
  <%= link_to "Show this post", @post, class: "btn btn-sm btn-outline-dark" %>
  <%= link_to "Back to posts", posts_path, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<% @posts.each do |post| %>
<div class="card my-5 p-5">
  <%= render post %>
  <p><%= link_to "Show post", post, class: "btn btn-sm btn-outline-dark" %></p>
</div>
<% end %>

<%= link_to "New post", new_post_path, class: "btn btn-sm btn-outline-dark" %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div class="btn-group">
  <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-sm btn-outline-dark" %>
  <%= link_to "Back to posts", posts_path, class: "btn btn-sm btn-outline-dark" %>
  <%= button_to "Destroy this post", @post, method: :delete, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/users/_form.html.erb
<div class="border rounded p-5 m-5">
  <%= simple_form_for(@user) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :password %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class="border rounded p-5 m-5">
  <h5 class="text-muted">
    Name
  </h5>
  <%= strip_tags(user.name.html_safe) %>

  <br><hr class="my-5">

  <h5 class="text-muted">
    Password
  </h5>
  <%= user.password %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div class="btn-group">
  <%= link_to "Show this user", @user, class: "btn btn-sm btn-outline-dark" %>
  <%= link_to "Back to users", users_path, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<% @users.each do |user| %>
  <div class="card my-5 p-5">
    <%= render user %>
    <p><%= link_to "Show user", user, class: "btn btn-sm btn-outline-dark" %></p>
  </div>
<% end %>

<%= link_to "New user", new_user_path, class: "btn btn-sm btn-outline-dark" %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div class="btn-group">
  <%= link_to "Edit this user", edit_user_path(@user), class: "btn btn-sm btn-outline-dark" %>
  <%= link_to "Back to users", users_path, class: "btn btn-sm btn-outline-dark" %>
  <%= button_to "Destroy this user", @user, method: :delete, class: "btn btn-sm btn-outline-dark" %>
</div>